<a href="/ecommerce/produtos/create"><input type="button" value="Novo Produto" title="Inserir novo produto."></a>	
<br><br>

<div class='panel panel-default'>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Marca</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Valor</th>
                <th>Margem de lucro</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($produtos as $produto) {
                ?>
                <tr>
                    <td><?= $produto->id; ?></td>
                    <td><?= $produto->marca->descricao; ?></td>
                    <td><?= $produto->nome; ?></td>
                    <td><?= $produto->descricao; ?></td>
                    <td><?= $produto->valor; ?></td>
                    <td><?= $produto->margem_de_lucro; ?></td>

                    <td> <a href="/ecommerce/produtos/update/id/<?= $produto->id ?>">
                            <span class="glyphicon glyphicon-pencil" title="Excluir registro"></span> </a></td>

                    <td> <a href="/ecommerce/produtos/delete/id/<?= $produto->id ?>">
                            <span class="glyphicon glyphicon-trash" title="Editar registro"></span> </a></td>
                </tr>

            <?php } ?>
        </tbody>
    </table>
</div>
